apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/goshipra/rag-mlops-pipeline
    newName: ghcr.io/goshipra/rag-mlops-pipeline
    newTag: 6dc9aa11a8de
commonLabels:
  environment: local

